server:
  port: 9020

logging:
  level:
    uk.gov.crowncommercial.dts.scale: DEBUG
    org.springframework: INFO

---
spring:
  profiles: local
server:
  servlet:
    context-path: /guided-match-service