server:
  port: 9020

logging:
  level:
    uk.gov.crowncommercial.dts.scale: DEBUG
    org.springframework: INFO
    # org.hibernate: DEBUG
    
 
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

external:
  decision-tree-service:    
    uri-templates:
      get-journey: "/journeys/{journey-uuid}"
      get-journey-question-outcome: "/journeys/{journey-uuid}/questions/{question-uuid}/outcome&modifier={modifier}"
    
---
spring:
  profiles: local
  datasource:
    # Credentials via environment variables ONLY.
    url: jdbc:postgresql://localhost:5432/postgres  
  
server:
  servlet:
    context-path: /guided-match-service
    
external:
  decision-tree-service:    
    url: http://127.0.0.1:9000/decision-tree